### ISSUE TITLE
Windows support checklist

### ISSUE THREAD

**Issue by whitequark** [GlasgowEmbedded/glasgow#231]
First-class Windows support is within our reach. The remaining issues are:
 - [x] python-libusb1 needs to ship binary wheels.
 - [ ] FX2 firmware needs to gain a workaround for Windows' inability to select configuration other than the first one. Or we should only use a single pipe everywhere else: #354
 - [x] Bitarray needs to be replaced with an in-tree, pure-Python implementation similar to `bits` from `glasgow.support.bits`. (#179)
 - [x] Right now, `yosys-abc` cannot be quieted, and it's pretty annoying. ~YoWASP needs to gain the ability to run `yosys-abc` in a subprocess.~ This was implemented using in-process stdout/stderr redirection.
 - [x] Glasgow needs to be able to discover the native and YoWASP toolchain, and fall back to YoWASP if the native toolchain is incomplete. (#353)

**Comment by whitequark** [comment]
Thanks to @mwkmwkmwk addressing #179 we only have a single item left until Windows support is exactly on par with every other supported platform! That one might take a while though.

I think this can be safely closed; I know a number of people use Glasgow on Windows with no issue and the minor performance regression compared to Linux that we'll need to eventually address architecturally isn't something most people will care about in first place.

:tada:
