### ISSUE TITLE
IC footprints

### ISSUE THREAD

**Issue by whitequark** [GlasgowEmbedded/glasgow#6]
- [x] ~Cypress CY7C68013A-56LTXC  QFN-56 (#15)~ (footprint merged in ~2 months, 3D package merged in ~2 months)
 - [x] ~ON Semi CAT24C256WI-GT3 SOIC-8 (#16)~ (symbol merged in 30 minutes)
 - [x] ~ON Semi CAT24M01WI-GT3 SOIC-8 (#7)~ (symbol merged in 3 days)
 - [x] ~Lattice ICE40UP5K-SG48ITR  QFN-48 (#8)~ (symbol merged in ~3 months)
 - [x] ~TI TPS73101DBVR SOT-23-5 (#9)~ (symbol merged in 1 day)
 - [x] ~TI DAC081C081CIMK TSOT-6 (#10)~ (symbol merged in 13 days)
 - [x] ~TI ADC081C021CIMM MSOP-8 (#11)~ (symbol merged in 3 days)
 - [x] ~ON Semi FXMA108BQX QFN-20 (#12)~ (footprint merged in 4 days, symbol merged in 13 days, 3D package merged in 14 days)
 - [x] ~Micrel MIC5355-S4YMME MSOP-8 (#13)~ (footprint merged in 21 days, symbol merged in 23 days)
 - [x] ~TI LM3880MFX-1AF SOT-23-5 (#14)~ (symbol merged in 3 hours)
 - [x] ~Lattice iCE40HX8K-BG121 121-ball caBGA (#28)~ (footprint merged in ~1.5 months, symbol merged in ~2.5 months)
 - [x] ~TI SN74LVC1T45 (#52)~ (footprint merged in 12 days, symbol merged in 12 days, 3D package merged in 28 days)
 - [x] ~TI TPD3S0x4 (#60)~ (symbol merged in 27 days)
 - [ ] Microchip ATECC508A (#84)
 - [ ] TI TCA9517 (#85)
 - [ ] TI PCA6408 (#105)
 - [ ] ON Semi MG2040 (#121)
 - [ ] TI TLV733/TLV755 (#134)

**Comment by whitequark** [comment]
No one has the bandwidth to upstream footprints.
